site:
  title: Alexey Bogdanov
  #url: https://docs.demo.com
  #start_page: ROOT::index.adoc тест 
urls:
  html_extension_style: drop
content:
  sources:
  - url: ./
    branches:
      - HEAD
    start_path: docs
ui:
  bundle:
    url: docs/ui/ui-bundle
output:
  dir: ./build
  clean: true